# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaltransaction',
            name='comment_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
