# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paypaltransaction_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptsycredential',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cryptsytransaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cryptsytransaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cryptsytransaction',
            name='sender_credential',
        ),
        migrations.DeleteModel(
            name='CryptsyCredential',
        ),
        migrations.DeleteModel(
            name='CryptsyTransaction',
        ),
    ]
