# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160102_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(max_length=8),
        ),
    ]
