# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160102_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_goal_lang_+', to='core.Language'),
        ),
        migrations.AddField(
            model_name='idea',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_idea_lang_+', to='core.Language'),
        ),
        migrations.AddField(
            model_name='need',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_need_lang_+', to='core.Language'),
        ),
        migrations.AddField(
            model_name='plan',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_plan_lang_+', to='core.Language'),
        ),
        migrations.AddField(
            model_name='step',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_step_lang_+', to='core.Language'),
        ),
        migrations.AddField(
            model_name='task',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_task_lang_+', to='core.Language'),
        ),
        migrations.AddField(
            model_name='work',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='_work_lang_+', to='core.Language'),
        ),
    ]
