# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160117_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='deliverables',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='step',
            name='investables',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
