# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160208_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='step',
            name='user_priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
