from core.views.comment import *
from core.views.definition import *
from core.views.goal import *
from core.views.idea import *
from core.views.need import *
from core.views.plan import *
from core.views.step import *
from core.views.task import *
from core.views.translation import *
from core.views.work import *
from core.views.views import *
